docs/tutorials/Git Version Control/Basics/Branch.md
docs/tutorials/Git Version Control/Basics/Index.md

Attempting fix for broken links build issue
Tested: Locally yes

fix: build issue fix with broken links to index.md

---

docs/tutorials/Git Version Control/Basics/Branch.md
docs/tutorials/Git Version Control/Basics/Commit.md
docs/tutorials/Git Version Control/Basics/Getting Started.md
docs/tutorials/Git Version Control/Basics/Git Basics.md
docs/tutorials/Git Version Control/Basics/Index.md
docs/tutorials/Git Version Control/Basics/Merge Conflicts.md
docs/tutorials/Git Version Control/Basics/Merging.md
docs/tutorials/Git Version Control/Basics/New Files.md
docs/tutorials/Git Version Control/Basics/Staging Area.md

Working linking to markdown pages in Git tutorial
Tested: Locally Yes

Feat  update tutorials section

---

docusaurus.config.js

Added instagram link to navbar
Tested: Yes

feat: Added link to club instagram on navbar

---

submodules_automation.sh

Quick fix to script to work from current dir instead of looking from root.
Tested: Yes Locally

fix: Minor Update submodules_automation.sh

---

submodules_automation.sh

Minor edits to submodules script for server and local usage. 
Tested: Yes Locally

fix: More edits to the submodules script

---

README.md
docusaurus.config.js

Updates to footer and minor edits to README
Test: Locally Yes

Chore  update footer

---

docusaurus.config.js
src/components/NavbarItems/AccountButton.js
src/pages/SignIn.js
src/pages/index.js
src/theme/NavbarItem/ComponentTypes.js

Moved FAQ to footer. 
Changed Socials to dropdown
Merged Engage links to one.

Navbar updates for smaller screen sizes

---

blog/A Developer's Story.md
blog/The Power of UniBot.md
blog/The Story Behind UniPath.io.md
blog/authors.yml
blog/tags.yml
docusaurus.config.js
package-lock.json
package.json

Few Shell blogs added.
Feel free to contribute to this over time!
Add more tags as needed in `blog/tags.yml`
Add yourself as an author into `blog/authors.yml`

feat: Reintroduced Blogs back to the website 

---

docusaurus.config.js

chore: Replace Engage link into socials dropdown

---

docs/Meeting Schedule.md

Fixed Meeting Calander link
Tested: Yes

chore: Update Calander link on meeting schedule

---

.github/workflows/deploy.yml

This pull request updates the existing GitHub Actions deployment workflow to include a build check for pull requests to the `main` branch.

Add build check for PRs

---

.github/workflows/deploy.yml

Reverts UMLCloudComputing/UMLCloudComputing.github.io#57

Revert "Add build check for PRs"

---

docs/projects/welcome.md
docs/tutorials/welcome.md
docusaurus.config.js
src/pages/index.js

chore: Replace link with button for about us, add missing welcome page for tutorials

---

src/pages/index.js

fix: Fix squished landing page button on mobile

---

docusaurus.config.js

Tested: Locally Yes 
closes #39

fix: Fix mish mash colormode on init launch

---

src/components/AvatarLarge.tsx
src/members_meta/members.json
src/pages/index.js

Member data is currently retrieved from a static json file. Can be adapted in the future to use async fetches from a remote file.

feat: Added member avatar component with modal functionality on landing page.

---

src/members_meta/members.json

Fix Minor typos in member json object

fix: Fix typos on member list

---

src/css/custom.css
src/pages/index.js

This is a preliminary design. Will be updated with future project showcases on the landing page. Potentially with split showcases instead of a giant hero banner. 
Tested: Locally Yes

feat: prelim design for adding UniBot iframe

---

docs/resources/UML Class Resources/welcome.mdx

Fixes a minor slug conflict.
Tested: Locally Yes

fix: Correct resources welcome page slug

---

README.md
docusaurus.config.js

Minor change to add announcement bar to page
Tested: Locally yes

Chore  add announcement banner

---

blog/Welcome to the Cloud Computing Club.mdx

Fix our projects section on blog post for new semester
Tested: Locally Yes

quickfix: Add missing bullet points to Our Projects section

---

.gitignore
docusaurus.config.js

chore: Update banner to kick-off meeting info

---

docusaurus.config.js

chore: Minor update to webpage banner

---

README.md

fix: Admonition correction attempt #2

---

README.md

fix: Readme text sizing issue

---

src/css/custom.css

Minor changes to color palate for the website to be based off club logo colors. 
N/A
- [x ] I confirm that no class materials, solutions, or professor-provided content are included without explicit permission.
Tested: Yes Locally

feat: Minor color palate changes

---

docs/activities/welcome.md
docs/projects/welcome.md
docs/resources/welcome.md
src/pages/index.js

Make welcome page slugs more specific.
N/A
N/A

chore: Slug updates to be more concise

---

docs/resources/UML Class Resources/COMP.1020 - Computing II/Exam Study Materials/Exam 2 Study Guide.mdx

Added the resources that I used to study for the second exam for comp 2.
- [x ] Study guide
- [ x] I confirm that no class materials, solutions, or professor-provided content are included without explicit permission.

docs: add comp 2 exam 2 study guide

---

docusaurus.config.js

chore: Updated Website announcement banner

---

src/components/AvatarLarge.tsx
src/members_meta/members.json

Added more important members to the member cards on the landing page
N/A
N/A

chore: Added a more members to landing page

---

docs/schedule/2024Fall/Week2.mdx
docs/schedule/2024Fall/Week3.mdx
src/css/custom.css

Added meeting recordings to notes for past 2 weeks.
N/A
N/A

chore: Added meeting video iframes

---

src/cards_meta/cards_data.json
src/components/PaperCard.tsx
src/css/custom.css
src/pages/index.js

Landing page info cards pull data from a meta json file. Makes it much more scalable and maintable to add more cards with consistent UI. 
Info cards are now scrollable rather than static cards. Better placement and more visually appealing use of space.
N/A
N/A

feat: Reorganized Info cards on landing page

---

src/css/custom.css

Corrects CSS for footer
N/A
N/A

fix: Correct footer css to be more specific

---

docusaurus.config.js

Added Youtube to Socials dropdown
N/A
N/A

chore: Added Youtube to socials dropdown

---

src/components/AvatarLarge.tsx
src/css/custom.css

Minor formatting change
N/A
N/A

chore: Center body text for member modals

---

static/meta_data/members_meta/members.json

Minor member metadata fix
N/A
N/A

fix: Correct member metadata

---

stream.js

Fix stream.js to read and process resource_repos.js

quickfix: Fix stream to use resources repos

---

remote_repos/resources_repos.json
stream.js

Correct spaces between name key in resources json file.

quickfix: Correct spacing issue on resources json file

---

remote_repos/project_repos.json

Added Immersion to list of repos in project_repos.json

chore/Added Immersion repo to list of project repos

---

remote_repos/project_repos.json

Reverts UMLCloudComputing/UMLCloudComputing.github.io#133

Revert "chore/Added Immersion repo to list of project repos"

---

docusaurus.config.js

Update the banner with current club events

chore: Updated banner with current club events

---

blog/Upcoming events in Week 8.mdx

Added new Blog post with week 8 details

chore: Added week 8 details as blog

---

blog/Upcoming events in Week 8.mdx

Remove website link, reduce redundancy

Update Upcoming events in Week 8.mdx

---

static/meta_data/members_meta/members.json

Updated the details on my own member modal

chore: Update member modal (Gurpreet)

---

static/meta_data/members_meta/members.json

Feat: Edit Member Details
Edited image link and description for Sebastian
- [x ] n/a

Feat: Edit Member Details

---

README.md
docs/schedule/2025Spring/2025Spring.mdx
docs/schedule/2025Spring/Week10.mdx
docs/schedule/2025Spring/Week11.mdx
docs/schedule/2025Spring/Week12.mdx
docs/schedule/2025Spring/Week13.mdx
docs/schedule/2025Spring/Week14.mdx
docs/schedule/2025Spring/Week2.mdx
docs/schedule/2025Spring/Week3.mdx
docs/schedule/2025Spring/Week4.mdx
docs/schedule/2025Spring/Week5.mdx
docs/schedule/2025Spring/Week6.mdx
docs/schedule/2025Spring/Week7.mdx
docs/schedule/2025Spring/Week9.mdx

Schedule updates and readme instruction updates

chore: Schedule updates and Readme correction for HTTPS

---

docs/schedule/2025Spring/2025Spring.mdx
docs/schedule/2025Spring/Week10.mdx
docs/schedule/2025Spring/Week11.mdx
docs/schedule/2025Spring/Week12.mdx
docs/schedule/2025Spring/Week13.mdx
docs/schedule/2025Spring/Week14.mdx
docs/schedule/2025Spring/Week2.mdx
docs/schedule/2025Spring/Week3.mdx
docs/schedule/2025Spring/Week4.mdx
docs/schedule/2025Spring/Week5.mdx
docs/schedule/2025Spring/Week6.mdx
docs/schedule/2025Spring/Week7.mdx
docs/schedule/2025Spring/Week9.mdx

Updates to Spring 2025 Schedule

chore: Minor updates to Spring 2025 schedule

---

docusaurus.config.js

Banner update with next meeting details

chore: Updated banner

---

docs/schedule/2025Spring/Week2.mdx

Minor correction to meeting notes

chore: Minor correction to meeting notes

---

docusaurus.config.js

Updated banner with details on next meeting

chore: Updated website banner with announcement for next meeting

---

docusaurus.config.js

chore: Updated banner, not changing schedule

---

docusaurus.config.js

Removed Banner, not needed as of late

chore: Removed banner

---

docs/schedule/2025Spring/Week10.mdx

chore: Updated Week 10 meeting notes

---

docs/schedule/2025Spring/Week13.mdx

chore: Week 13 Meeting notes, recording, election details

---

docs/schedule/2025Spring/Week14.mdx

Week 14 details updates, elections, game night, etc.

chore: Update Week 14 Meeting details

---

remote_repos/project_repos.json
remote_repos/resources_repos.json
src/pages/index.js

Added docs for Immersion dashboard

chore: Updated and added references to various club projects

---

docs/schedule/2025Summer/Week3.mdx

Updates Week 3 meeting notes for Summer 2025

chore: Summer Week 3 notes updated

---

docs/schedule/2023Fall.mdx
docs/schedule/2024Fall/2024Fall.mdx
docs/schedule/2024Spring.mdx
docs/schedule/2025Spring/2025Spring.mdx
src/css/custom.css

Added meeting pictures from past meetings. 
Image links are depending on UML Engage infra. As they shift out of that infra, those links will need to be updated. 
Implementation is very simple with no on-click modal support. "Mobile" compliant with dynamic resizing by markdown. 
Certainly could benefit from feature improvement in the future for better UI.

chore: Added meeting pictures from past meetings. Simple implementation

---

docs/schedule/2025Fall/2025Fall.mdx

chore: Removed a space
